### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by coldfix**
Hi,

I think this application is well suited to be run from a docker image, and since this might be useful for others, I think it would make sense to include a Dockerfile here. However, I can understand if you prefer to leave this out. Anyway, thanks for the wonderful tool!

Best, Thomas

### CODE REVIEW

**Comment by elisescu** [comment]
Thanks for your PR, Thomas! I agree with the suggestion - wanted to add it myself at some point.
I am very happy to hear you tried the tool, and liked it :)

**Comment by coldfix** [comment]
Hi, and many thanks for merging!

I've got one question. I tried to setup an SSL proxy through nginx but it seems to work only for the webinterface (port 5000). My guess is that the client protocol (port 6543) is not http? If so, I'll probably need something like the [this](https://stackoverflow.com/a/35521557/650222). Is that right,  / how did you setup SSL on your server?

Best, Thomas

**Comment by elisescu** [comment]
Hi! Yeah, I am using that nginx stream directive. I've put this [gist](https://gist.github.com/elisescu/d945ba2460f15190b6faff757ed49d37) a while ago, dumping the relevant parts of my nginx config for somebody else - maybe you can find something useful in there.
I hope to get some free time to add this information in a proper doc in the actual project at some point soon.

**Comment by coldfix** [comment]
Thanks, much appreciated!

**Pull request merged**
