### PR TITLE
Use nerd font patched Source Code Pro as default font for better rendering of glyphs

### LINKED ISSUE #9: Use a more fully featured font-face, for rendering powerline-style elements.
My tmux statusbar & vim statusbars use unicode characters not supported by all fonts. 

This style of config provides a more GUI-like feeling in the terminal & better context-cues as to what's what. 

[asciicast](https://asciinema.org/a/QS70xBwEQKcMLm2AH5UrZM3Ko)

Presently tty-share doesn't support these symbols, but font-faces like [source code pro](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro/1.050R-it) do, so if a supportive fontface is added to the stylesheet, you should be able to support more terminal envs

### PR DESCRIPTION
**Pull request by strazto**
This is a squash/merge cleanup of #10 

Resolves #9 

Besides the addition of a lot of assets, the changes involved are relatively minor- A new npm dependency (`file-loader`) , stylesheet changes & reconf of tty-reciever's `fontFamily`.

Oh, and a python script that helped generate the stylesheet from the TTF filenames that could probably be removed.

### CODE REVIEW

**Comment by moobyfr** [comment]
These fonts are released under the OFL terms
https://github.com/adobe-fonts/source-code-pro

**Comment by strazto** [comment]
> These fonts are released under the OFL terms
> https://github.com/adobe-fonts/source-code-pro

Indeed. 

I actually took note of the license in the stylesheet on this PR - is there something the matter with it? 

It's a fairly permissive license and we're definitely within its terms to use it.

**Comment by strazto** [comment]
@elisescu this is ready to merge, pending your review

**Comment by elisescu** [comment]
@matthewstrasiotto super, getting it in right away. Thanks :) !

**Review by elisescu — APPROVED** [review]

**Pull request merged**
